### PR TITLE
New Flat Icons (round)

### PR DESCRIPTION
**Pull request by EnderNightLord-ChromeBook**
zork
octave
ubuntu
libreoffice
kali
git
gimp
firefox
debian
arch

### CODE REVIEW

**Comment by EnderNightLord-ChromeBook** [comment]
oh yes and made them 256 x 256

**Comment by corbinlc** [comment]
My preference has been for icons similar to the ones I have created.  Transparent around the edge instead for in a circle or otherwise surrounded by some background shape and color.  Gimp and LibreOffice were done by someone else and I have not revisited them, but when I do, I will make them similar to what we have for Debian, Arch, Kali etc.  As such, I am going to close this pull request.  I am not a graphic designer or anything like that, and may not know the best decision here, but I am going to stick with my preference.

**Comment by EnderNightLord-ChromeBook** [comment]
I respect your choice.

**Comment by EnderNightLord-ChromeBook** [comment]
could there be a icon preference? so you could pick between classic and flat icons?

**Pull request closed without merging**
