### PR TITLE
Add Desktops To Apps (Xfce4, Mate And Lxde)

### PR DESCRIPTION
**Pull request by EnderNightLord-ChromeBook**
Adds:
* Mate Desktop
* Xfce4 Desktop
* Lxde Desktop

### CODE REVIEW

**Comment by corbinlc** [comment]
Can you break python idle into its own PR?  We generally want 1 app per PR, so we can test them and pull them in individually.

For the desktops, that is great.  We are going to hold off on pulling that in for a couple of reasons 1) right now those all crash on certain Huawei devices.  2) Our performance is too slow and this can take too long to finish.  I am working on improvements to address both of these issues.  After that, we will probably switch from twm->lxde by default.  Then having other desktops as single click apps would make a lot of sense.

**Comment by EnderNightLord-ChromeBook** [comment]
Ok... Would You Like Me To Close?

**Comment by corbinlc** [comment]
No.  We can just keep it open until we know what we want to do.

**Comment by EnderNightLord-ChromeBook** [comment]
got it.

**Comment by corbinlc** [comment]
I added lxde and xfce apps.  I am not going to add the others right now, as I am getting closer to changing how distro are built and how people can choose a different default desktop.

**Comment by EnderNightLord-ChromeBook** [comment]
Ok... Good to hear from you.

**Pull request closed without merging**
